CREATE TABLE "gamemode" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "gamemode" varchar
);

CREATE TABLE "message_type" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar
);

CREATE TABLE "dimension" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dimension" varchar
);

CREATE TABLE "biome" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "biome" varchar
);

CREATE TABLE "item" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "item" varchar
);

CREATE TABLE "player" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" varchar(32) UNIQUE,
  "username" varchar(32),
  "reputation" int,
  "added" timestamp,
  "active" timestamp
);

CREATE TABLE "server" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "ip" varchar,
  "added" timestamp,
  "active" timestamp
);

CREATE TABLE "server_player" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "player" int,
  "server" int,
  "added" timestamp,
  "active" timestamp
);

CREATE TABLE "messages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" int,
  "message" varchar,
  "from" int,
  "to" int,
  "sent" timestamp
);

CREATE TABLE "chunk" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "server" int,
  "dimension" int,
  "biome" int,
  "cx" int,
  "cz" int,
  "ch" int
);

CREATE TABLE "network_data" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "player" int,
  "ip" varchar,
  "user_agent" varchar,
  "via" varchar,
  "forwarded" varchar,
  "added" timestamp,
  "active" timestamp
);

CREATE TABLE "inventory" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "server_player" int,
  "slot_selected" int
);

CREATE TABLE "item_instance" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "inventory" int,
  "item" int,
  "slot" int,
  "count" int,
  "custom" varchar
);

CREATE TABLE "attributes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "server_player" int,
  "health" int,
  "hunger" int,
  "breath" int,
  "protection" int,
  "saturation" int,
  "exhaustion" int,
  "exp_level" int,
  "exp_prog" float,
  "gamemode" int,
  "ping" int,
  "fps" int
);

CREATE TABLE "effects" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "server_player" int
);

CREATE TABLE "effect" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "effect" varchar,
  "type" varchar
);

CREATE TABLE "effect_instance" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "effects" int,
  "effect" int,
  "duration" int,
  "strength" int
);

CREATE TABLE "position" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "server_player" int,
  "position" float[3],
  "velocity" float[3],
  "dimension" int,
  "sneaking" bool,
  "sprinting" bool,
  "swimming" bool,
  "crawling" bool,
  "grounded" bool,
  "fallflying" bool,
  "added" timestamp
);

CREATE TABLE "nearby" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "position" int,
  "player" int
);

ALTER TABLE "server_player" ADD FOREIGN KEY ("player") REFERENCES "player" ("id");

ALTER TABLE "server_player" ADD FOREIGN KEY ("server") REFERENCES "server" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("from") REFERENCES "server_player" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("to") REFERENCES "server_player" ("id");

ALTER TABLE "chunk" ADD FOREIGN KEY ("server") REFERENCES "server" ("id");

ALTER TABLE "network_data" ADD FOREIGN KEY ("player") REFERENCES "player" ("id");

ALTER TABLE "item_instance" ADD FOREIGN KEY ("inventory") REFERENCES "inventory" ("id");

ALTER TABLE "item_instance" ADD FOREIGN KEY ("item") REFERENCES "item" ("id");

ALTER TABLE "inventory" ADD FOREIGN KEY ("server_player") REFERENCES "server_player" ("id");

ALTER TABLE "attributes" ADD FOREIGN KEY ("server_player") REFERENCES "server_player" ("id");

ALTER TABLE "effect_instance" ADD FOREIGN KEY ("effect") REFERENCES "effect" ("id");

ALTER TABLE "effect_instance" ADD FOREIGN KEY ("effects") REFERENCES "effects" ("id");

ALTER TABLE "effects" ADD FOREIGN KEY ("server_player") REFERENCES "server_player" ("id");

ALTER TABLE "attributes" ADD FOREIGN KEY ("gamemode") REFERENCES "gamemode" ("id");

ALTER TABLE "position" ADD FOREIGN KEY ("server_player") REFERENCES "server_player" ("id");

ALTER TABLE "chunk" ADD FOREIGN KEY ("dimension") REFERENCES "dimension" ("id");

ALTER TABLE "chunk" ADD FOREIGN KEY ("biome") REFERENCES "biome" ("id");

ALTER TABLE "position" ADD FOREIGN KEY ("dimension") REFERENCES "dimension" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("type") REFERENCES "message_type" ("id");

ALTER TABLE "nearby" ADD FOREIGN KEY ("position") REFERENCES "position" ("id");

ALTER TABLE "nearby" ADD FOREIGN KEY ("player") REFERENCES "player" ("id");
