services:
  postgres:
    environment:
      POSTGRES_USER: connectorlib
      POSTGRES_PASSWORD: connectorlib
      POSTGRES_DB: connectorlib
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - db_network
    container_name: postgres
    restart: on-failure
    image: postgres

  pgbouncer:
    environment:
      DATABASE_URL: postgres://connectorlib:connectorlib@postgres:5432/connectorlib
      POOL_MODE: transaction
      MAX_DB_CONNECTIONS: 100
      DEFAULT_POOL_SIZE: 40
      AUTH_TYPE: scram-sha-256
    ports:
      - 5432:5432
    depends_on:
      - postgres
    networks:
      - db_network
    container_name: pgbouncer
    restart: on-failure
    image: rmccaffrey/pgbouncer

  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: connectorlib@local.host
      PGADMIN_DEFAULT_PASSWORD: connectorlib
      PGADMIN_DISABLE_POSTFIX: true
    ports:
      - 8080:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - db_network
    depends_on:
      - postgres
      - pgbouncer
    container_name: pgadmin
    restart: on-failure
    image: dpage/pgadmin4

networks:
  db_network:
    driver: bridge

volumes:
  postgres:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data
  pgadmin:
