version: '3'
services:
  postgres:
    environment:
      POSTGRES_USER: connectorlib
      POSTGRES_PASSWORD: connectorlib
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - db_network
    container_name: postgres
    image: postgres

  pgadmin:
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: connectorlib@local.host
      PGADMIN_DEFAULT_PASSWORD: connectorlib
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - db_network
    depends_on:
      - postgres
    container_name: pgadmin
    image: dpage/pgadmin4

networks:
  db_network:
    driver: bridge

volumes:
  postgres:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data
  pgadmin:
