CREATE TABLE "players" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "uuid" varchar NOT NULL,
  "username" varchar,
  "network_data_id" int UNIQUE,
  "first_seen" timestamp,
  "last_seen" timestamp
);

CREATE TABLE "network_data" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "ip_address" varchar,
  "user_agent" varchar,
  "via" varchar,
  "forwarded" varchar
);

CREATE TABLE "servers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" varchar,
  "ip_address" varchar,
  "chunks_id" int UNIQUE,
  "server_uptime_id" int UNIQUE
);

CREATE TABLE "chunks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "surface_blocks_id" int UNIQUE,
  "dimension" varchar,
  "biome" varchar,
  "surface_y" int,
  "chunk_x" int,
  "chunk_z" int
);

CREATE TABLE "surface_blocks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" varchar,
  "global_y" int,
  "offset_x" int,
  "offset_z" int
);

CREATE TABLE "server_players" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "player_id" int UNIQUE NOT NULL,
  "server_id" int UNIQUE NOT NULL,
  "first_seen" timestamp,
  "last_seen" timestamp
);

CREATE TABLE "server_uptime" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "total_uptime" int,
  "last_online" timestamp
);

CREATE TABLE "sessions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "token" varchar NOT NULL,
  "player_id" int UNIQUE,
  "created" timestamp,
  "last_used" timestamp
);

COMMENT ON COLUMN "network_data"."forwarded" IS 'JSON array, eg ["1.2.3.4","5.6.7.8"]';

ALTER TABLE "server_players" ADD FOREIGN KEY ("player_id") REFERENCES "players" ("id");

ALTER TABLE "server_players" ADD FOREIGN KEY ("server_id") REFERENCES "servers" ("id");

ALTER TABLE "network_data" ADD FOREIGN KEY ("id") REFERENCES "players" ("network_data_id");

ALTER TABLE "sessions" ADD FOREIGN KEY ("player_id") REFERENCES "players" ("id");

ALTER TABLE "chunks" ADD FOREIGN KEY ("id") REFERENCES "servers" ("chunks_id");

ALTER TABLE "surface_blocks" ADD FOREIGN KEY ("id") REFERENCES "chunks" ("surface_blocks_id");

ALTER TABLE "server_uptime" ADD FOREIGN KEY ("id") REFERENCES "servers" ("server_uptime_id");
