from typing import Type
from messages import (
    BaseHandler,
    ChatData,
    ChunkEvent,
    IdentityEvent,
    NetworkData,
    PlayerArmor,
    PlayerBreath,
    PlayerEffects,
    PlayerExperience,
    PlayerFPS,
    PlayerGamemode,
    PlayerHealth,
    PlayerHotbar,
    PlayerHunger,
    PlayerJoin,
    PlayerMovement,
    PlayerPing,
    PlayerQuit,
    PlayerRespawn,
    PositionData,
    SystemChatData,
)

HANDLERS: dict[str, Type[BaseHandler.BaseHandler]] = {
    "ChatData": ChatData.ChatData,
    "ChunkData": ChunkEvent.ChunkData,
    "IdentityChallenge": IdentityEvent.IdentityChallenge,
    "IdentityRequest": IdentityEvent.IdentityRequest,
    "NetworkData": NetworkData.NetworkData,
    "PlayerArmor": PlayerArmor.PlayerArmor,
    "PlayerBreath": PlayerBreath.PlayerBreath,
    "PlayerEffects": PlayerEffects.PlayerEffects,
    "PlayerExperience": PlayerExperience.PlayerExperience,
    "PlayerFPS": PlayerFPS.PlayerFPS,
    "PlayerGamemode": PlayerGamemode.PlayerGamemode,
    "PlayerHealth": PlayerHealth.PlayerHealth,
    "PlayerHotbar": PlayerHotbar.PlayerHotbar,
    "PlayerHunger": PlayerHunger.PlayerHunger,
    "PlayerJoin": PlayerJoin.PlayerJoin,
    "PlayerMovement": PlayerMovement.PlayerMovement,
    "PlayerPing": PlayerPing.PlayerPing,
    "PlayerQuit": PlayerQuit.PlayerQuit,
    "PlayerRespawn": PlayerRespawn.PlayerRespawn,
    "PositionData": PositionData.PositionData,
    "SystemChatData": SystemChatData.SystemChatData,
}
